//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_School
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SchoolEntities : DbContext
    {
        public SchoolEntities()
            : base("name=SchoolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<subject> subjects { get; set; }
    
        [DbFunction("SchoolEntities", "fn_Classlist")]
        public virtual IQueryable<fn_Classlist_Result> fn_Classlist()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_Classlist_Result>("[SchoolEntities].[fn_Classlist]()");
        }
    
        [DbFunction("SchoolEntities", "fn_Studentslist")]
        public virtual IQueryable<fn_Studentslist_Result> fn_Studentslist()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_Studentslist_Result>("[SchoolEntities].[fn_Studentslist]()");
        }
    
        [DbFunction("SchoolEntities", "fn_Subjectslist")]
        public virtual IQueryable<fn_Subjectslist_Result> fn_Subjectslist()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_Subjectslist_Result>("[SchoolEntities].[fn_Subjectslist]()");
        }
    
        public virtual int sp_DeleteClass(Nullable<int> p_classid)
        {
            var p_classidParameter = p_classid.HasValue ?
                new ObjectParameter("p_classid", p_classid) :
                new ObjectParameter("p_classid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeleteClass", p_classidParameter);
        }
    
        public virtual int sp_DeleteStudents(Nullable<int> p_studentid)
        {
            var p_studentidParameter = p_studentid.HasValue ?
                new ObjectParameter("p_studentid", p_studentid) :
                new ObjectParameter("p_studentid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeleteStudents", p_studentidParameter);
        }
    
        public virtual int sp_DeleteSubjects(Nullable<int> p_subjectid)
        {
            var p_subjectidParameter = p_subjectid.HasValue ?
                new ObjectParameter("p_subjectid", p_subjectid) :
                new ObjectParameter("p_subjectid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeleteSubjects", p_subjectidParameter);
        }
    
        public virtual int sp_FindClass(Nullable<int> p_classid, ObjectParameter p_classname)
        {
            var p_classidParameter = p_classid.HasValue ?
                new ObjectParameter("p_classid", p_classid) :
                new ObjectParameter("p_classid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_FindClass", p_classidParameter, p_classname);
        }
    
        public virtual ObjectResult<sp_FindStudents_Result> sp_FindStudents(Nullable<int> p_studentid, ObjectParameter p_classid, ObjectParameter p_studentname, ObjectParameter p_address, ObjectParameter p_email)
        {
            var p_studentidParameter = p_studentid.HasValue ?
                new ObjectParameter("p_studentid", p_studentid) :
                new ObjectParameter("p_studentid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_FindStudents_Result>("sp_FindStudents", p_studentidParameter, p_classid, p_studentname, p_address, p_email);
        }
    
        public virtual ObjectResult<sp_FindSubjects_Result> sp_FindSubjects(Nullable<int> p_subjectid, ObjectParameter p_classid, ObjectParameter p_subjectname)
        {
            var p_subjectidParameter = p_subjectid.HasValue ?
                new ObjectParameter("p_subjectid", p_subjectid) :
                new ObjectParameter("p_subjectid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_FindSubjects_Result>("sp_FindSubjects", p_subjectidParameter, p_classid, p_subjectname);
        }
    
        public virtual int sp_UpdateClass(Nullable<int> p_classid, string p_classname)
        {
            var p_classidParameter = p_classid.HasValue ?
                new ObjectParameter("p_classid", p_classid) :
                new ObjectParameter("p_classid", typeof(int));
    
            var p_classnameParameter = p_classname != null ?
                new ObjectParameter("p_classname", p_classname) :
                new ObjectParameter("p_classname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateClass", p_classidParameter, p_classnameParameter);
        }
    
        public virtual int sp_UpdateStudents(Nullable<int> p_studentid, Nullable<int> p_classid, string p_studentname, string addres, string email)
        {
            var p_studentidParameter = p_studentid.HasValue ?
                new ObjectParameter("p_studentid", p_studentid) :
                new ObjectParameter("p_studentid", typeof(int));
    
            var p_classidParameter = p_classid.HasValue ?
                new ObjectParameter("p_classid", p_classid) :
                new ObjectParameter("p_classid", typeof(int));
    
            var p_studentnameParameter = p_studentname != null ?
                new ObjectParameter("p_studentname", p_studentname) :
                new ObjectParameter("p_studentname", typeof(string));
    
            var addresParameter = addres != null ?
                new ObjectParameter("addres", addres) :
                new ObjectParameter("addres", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateStudents", p_studentidParameter, p_classidParameter, p_studentnameParameter, addresParameter, emailParameter);
        }
    
        public virtual int sp_UpdateSubjects(Nullable<int> p_subjectid, Nullable<int> p_classid, string p_subjectname)
        {
            var p_subjectidParameter = p_subjectid.HasValue ?
                new ObjectParameter("p_subjectid", p_subjectid) :
                new ObjectParameter("p_subjectid", typeof(int));
    
            var p_classidParameter = p_classid.HasValue ?
                new ObjectParameter("p_classid", p_classid) :
                new ObjectParameter("p_classid", typeof(int));
    
            var p_subjectnameParameter = p_subjectname != null ?
                new ObjectParameter("p_subjectname", p_subjectname) :
                new ObjectParameter("p_subjectname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateSubjects", p_subjectidParameter, p_classidParameter, p_subjectnameParameter);
        }
    }
}
